#!/bin/bash

#try running: npm install -g watchify browser-sync babel-cli uglify-js
echo "Building Handler..." && \

mkdir -p dist && \

echo "Building CSS..." && \
lessc src/style.less src/style.css && \

echo "Transpiling..." && \
babel --presets es2015 --source-type 'module' --out-dir '.transpiled' src && \

echo "Browserifying..." && \
browserify .transpiled/handlers/custom/index.js | uglifyjs -cm > dist/handler.min.js && \
browserify .transpiled/loadPreact.js | uglifyjs -cm > dist/loadPreact.js && \

gulp index && \

echo "Built handler.js"
